name: uangku
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  sqflite: ^2.4.2
  uuid: ^4.5.2
  path: ^1.8.3
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  sqflite_common_ffi: ^2.3.6
  fl_chart: ^1.1.1
  build_runner: ^2.4.9 # Versi terbaru (atau versi yang sesuai)
  freezed: ^2.5.2 # Versi terbaru (atau versi yang sesuai)
  json_serializable: ^6.7.1 # Versi terbaru (atau versi yang sesuai)
  freezed_annotation: ^2.4.4
  collection: ^1.19.1
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
